/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rpn;

import jexer.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        TApplication app = new TApplication(TApplication.BackendType.SWING);
        app.run();

        System.out.println(new App().getGreeting());
    }
}
